name: windows_x86_64

on: "push"

jobs:
  build_windows_x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Set up Premake for Windows
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Build on Windows
        shell: cmd
        run: |
          premake5 vs2022
          msbuild KingdomsAndEmpires.sln -property:Configuration=release
        working-directory: D:/a/KingdomsAndEmpires/KingdomsAndEmpires