name: linux_x86_64

on: "push"

jobs:
  build_linux_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install X11 development libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev

      - name: Set up Premake for Linux
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Build on Linux
        run: |
          premake5 gmake2
          make
        working-directory: .
