name: macOS_arm64

on:
  schedule:
    # Run nightly at 2:00 AM UTC
    - cron: "0 2 * * *"

jobs:
  build_macos_arm64:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest]
        arch: [ARM64]

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up Premake for macOS
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Build on macOS
        run: |
          premake5 gmake
          make clean
          make
        working-directory: .