name: linux_x86_64

on:
  push:
    branches: # Runs on pushes to any branch
      - '**'
  schedule:
    # Run nightly at 2:00 AM UTC
    - cron: "0 2 * * *"

jobs:
  build_linux_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install OpenGL and X11 development libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev xorg-dev

      - name: Set up Premake for Linux
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Build on Linux
        run: |
          premake5 gmake2
          make clean
          make
        working-directory: .