name: Code Coverage

on: 
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Build Environment
      run: sudo apt-get update && sudo apt-get install -y g++ lcov

    - name: Build Project
      run: |
        make clean || true
        make

    - name: Run Tests and Collect Coverage
      run: |
        ./run_tests
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}