name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests and Collect Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y lcov g++

      - name: Build project
        run: |
          make clean
          make

      - name: Run tests
        run: ./run_tests # Replace with your test executable

      - name: Generate coverage report
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/test/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.info
          flags: unittests
          fail_ci_if_error: true